import a from './01.jpg';
import b from './02.jpg';
import c from './03.jpg';
import d from './04.jpg';
import e from './05.jpg';
import f from './06.jpg';
import g from './07.jpg';
import h from './08.jpg';
import i from './09.jpg';
import j from './10.jpg';
import k from './11.jpg';
import l from './12.jpg';
import m from './13.jpg';
import n from './14.jpg';
import o from './15.jpg';
import p from './16.jpg';
import naac from './NaacA+.png'
import naacA from './NAACA+logo.png'
import completeLogo from './logo.png'
import logo from './PupLogo.png'
import certificate from './Certificate.jpeg'
import PupMainGate from './PupMainGate.png'
import PupBuilding from "./PupBuilding.png"
import youtube from './youtube.svg'
import instagram from './instagram.svg'
import linkedin from './linkedin.svg'
import facebook from './facebook.svg'

export { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p,naac,naacA,completeLogo, logo,certificate,PupMainGate,PupBuilding,youtube,instagram,linkedin,facebook };